# Generated by Django 3.0.3 on 2020-02-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursystem', '0002_attractions_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='title',
            new_name='name',
        ),
    ]
