# Generated by Django 3.0.3 on 2020-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursystem', '0003_auto_20200225_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='attractions',
            old_name='name',
            new_name='at_name',
        ),
    ]
