# Generated by Django 3.0.3 on 2020-02-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursystem', '0006_product_productcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcat',
        ),
    ]
