# Generated by Django 3.0.3 on 2020-02-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursystem', '0007_remove_product_productcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='toursystem.ProductCat'),
            preserve_default=False,
        ),
    ]
