# Generated by Django 3.0.3 on 2020-02-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursystem', '0009_auto_20200226_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='description',
            new_name='other',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='price',
            new_name='time',
        ),
    ]
